name = "bus-arrival-worker"
main = "bus-arrival-worker.js"
type = "modules"
account_id = "4796a78c1804791b739f97bb336bab79"
compatibility_date = "2025-09-26"

[env.production]
workers_dev = false
# Worker 独立绑定到 busapi 子域
routes = ["busapi.0515364.xyz/*"]

[observability.logs]
enabled = true