name = "bus-arrival-worker"
main = "bus-arrival-worker.js"
type = "modules"
account_id = "4796a78c1804791b739f97bb336bab79"
compatibility_date = "2025-09-26"

[env.production]
workers_dev = false
# 只为 /busarrival/* 路径绑定 Worker
routes = ["bus.0515364.xyz/busarrival*"]

[observability.logs]
enabled = true