name: Deploy Bus Arrival Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Wrangler
        run: npm install -g wrangler

      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          LTA_API_KEY_BUS: ${{ secrets.LTA_API_KEY }}
        run: wrangler publish bus-arrival-worker.js --name bus-arrival-worker